site_name: My Documentation
#site_url: https://mydomain.org/mysite
nav:
- Головна:
    - index.md
- Корисні посилання:
    - url.md
theme:
  name: material
  language: uk
  features:
    - search.highlight
    - navigation.footer
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Темний
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Світлий