site_name: My Documentation
#site_url: https://mydomain.org/mysite

nav:
- Головна: index.md
- Написання документації:
  - Markdown Basic: Markdown_Cheatsheet.md
  - MkDocs: mkdocs.md
  - Sphinx: sphinx.md
- GIT:
  - Корисні посилання: GIT/git_links.md
  - Основні поняття GIT: GIT/git.md
  - Термінологія GIT: GIT/terminology.md
- PYTHON: 
  - Корисні посилання: PYTHON/python_links.md
- LINUX:
  - Корисні посилання: LINUX/linux_links.md
  - ЗАГАЛЬНЕ: LINUX/linux.md
- Корисні посилання:
  - ЗАГАЛЬНЕ: LINKS/links_basic.md
  - ENGLISH: LINKS/links_english.md
  - ІНФОРМАТИКА: LINKS/links_cs.md
  - ІНСТРУМЕНТИ : LINKS/links_tools.md
  - PYTHON: LINKS/links_python.md
  - ВАЖЛИВІ БАЗОВІ ТЕМИ: LINKS/links_important_subjects.md
  - БАЗИ ДАНИХ: LINKS/links_databases.md
  - GIT: LINKS/links_git.md
  - LINUX: LINKS/links_linux.md
  - РОБОЧИЙ ПРОЦЕС: LINKS/links_workflow.md
  - ДРОНИ: LINKS/links_drones.md


theme:
  name: material
  language: uk
  features:
    - search.highlight
    - navigation.footer
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Темний
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Світлий
